---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcmicroservice
  labels:
    app: grpcmicroservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: grpcmicroservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grpcmicroservice
    spec:
      containers:
      - name: grpcmicroservice
        image: grpcmicroservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: grpcmicroservice-env
        - secretRef:
            name: grpcmicroservice-secrets
      terminationGracePeriodSeconds: 180